// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYCi-dZe9TE41R5B8Wid8pg6PVtWuoHE8',
    appId: '1:915400744363:web:500ced47406b81be5f46ee',
    messagingSenderId: '915400744363',
    projectId: 'agroucl',
    authDomain: 'agroucl.firebaseapp.com',
    databaseURL: 'https://agroucl-default-rtdb.firebaseio.com',
    storageBucket: 'agroucl.appspot.com',
    measurementId: 'G-MH11N45216',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs_MKTetKtx71W8GOmPzVy63zp1-Gp8BM',
    appId: '1:915400744363:android:dde3e1c7934652595f46ee',
    messagingSenderId: '915400744363',
    projectId: 'agroucl',
    databaseURL: 'https://agroucl-default-rtdb.firebaseio.com',
    storageBucket: 'agroucl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYkIiNrnBZxJjF4uT3z1BqKyiAZCZR0XI',
    appId: '1:915400744363:ios:60e0793d4878312e5f46ee',
    messagingSenderId: '915400744363',
    projectId: 'agroucl',
    databaseURL: 'https://agroucl-default-rtdb.firebaseio.com',
    storageBucket: 'agroucl.appspot.com',
    iosBundleId: 'com.example.projetoAgrouclapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYkIiNrnBZxJjF4uT3z1BqKyiAZCZR0XI',
    appId: '1:915400744363:ios:60e0793d4878312e5f46ee',
    messagingSenderId: '915400744363',
    projectId: 'agroucl',
    databaseURL: 'https://agroucl-default-rtdb.firebaseio.com',
    storageBucket: 'agroucl.appspot.com',
    iosBundleId: 'com.example.projetoAgrouclapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYCi-dZe9TE41R5B8Wid8pg6PVtWuoHE8',
    appId: '1:915400744363:web:8ab676e7d981b5f35f46ee',
    messagingSenderId: '915400744363',
    projectId: 'agroucl',
    authDomain: 'agroucl.firebaseapp.com',
    databaseURL: 'https://agroucl-default-rtdb.firebaseio.com',
    storageBucket: 'agroucl.appspot.com',
    measurementId: 'G-BTETJP8FG4',
  );
}
